const state = { view: 'ask', docs: [], filter: 'ทั้งหมด', subcategory: 'ทั้งหมด', tag: 'ทั้งหมด', query: '', stats: {}, history: [], isAdmin: false };
const $ = (s) => document.querySelector(s);
let supabaseClient = null;
async function apiFetch(path, options = {}) {
  const { data } = supabaseClient ? await supabaseClient.auth.getSession() : { data: {} };
  const headers = new Headers(options.headers || {});
  if (data.session?.access_token) headers.set('Authorization', `Bearer ${data.session.access_token}`);
  return fetch(path, { ...options, headers });
}
function loginView(message = '') { return `<main class="auth-page"><div class="auth-card"><div class="seal">ก</div><span class="section-kicker">สิทธิพร้อม · กสม.</span><h1>เข้าสู่ระบบ</h1><p>กรุณาเข้าสู่ระบบเพื่อใช้งานฐานความรู้และเอกสารภายในสำนักงาน</p><form id="loginForm"><label>อีเมล<input id="email" type="email" autocomplete="email" required></label><label>รหัสผ่าน<input id="password" type="password" autocomplete="current-password" minlength="6" required></label><div id="authMessage" class="auth-message">${message}</div><button class="search-btn" type="submit">เข้าสู่ระบบ <span>${glyph('arrow')}</span></button></form><button class="auth-secondary" id="signup">สร้างบัญชีใหม่</button></div></main>`; }
function renderLogin(message = '') { document.querySelector('#app').innerHTML = loginView(message); document.querySelector('#loginForm').onsubmit = async (event) => { event.preventDefault(); const button = event.target.querySelector('button'); button.disabled = true; const { error } = await supabaseClient.auth.signInWithPassword({ email: $('#email').value, password: $('#password').value }); if (error) { renderLogin(error.message); return; } await init(); }; document.querySelector('#signup').onclick = async () => { const email = $('#email').value; const password = $('#password').value; if (!email || password.length < 6) return renderLogin('กรอกอีเมลและรหัสผ่านอย่างน้อย 6 ตัวอักษรก่อนสมัคร'); const { error } = await supabaseClient.auth.signUp({ email, password }); renderLogin(error ? error.message : 'สมัครสำเร็จ กรุณาตรวจอีเมลเพื่อยืนยันบัญชี'); }; }
async function initAuth() { const config = await (await fetch('/api/config')).json(); if (!config.supabaseUrl || !config.supabaseKey || !window.supabase) return renderLogin('ระบบยังไม่ได้ตั้งค่า Supabase Auth'); supabaseClient = window.supabase.createClient(config.supabaseUrl, config.supabaseKey); const { data } = await supabaseClient.auth.getSession(); if (!data.session) return renderLogin(); state.user = data.session.user; const me = await fetch('/api/me'); state.isAdmin = me.ok ? Boolean((await me.json()).isAdmin) : false; supabaseClient.auth.onAuthStateChange((_event, session) => { state.user = session?.user || null; if (!state.user) renderLogin(); }); await init(); }
const glyph = (n) => ({search:'⌕', library:'▦', history:'◷', upload:'↥', settings:'⚙', arrow:'↗', check:'✓', shield:'◈', file:'▤', close:'×'}[n] || '•');
function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char])); }
function toArabicDigits(value) { return String(value ?? '').replace(/[๐-๙]/g, digit => String('๐๑๒๓๔๕๖๗๘๙'.indexOf(digit))); }
function cleanUiText(value) { return toArabicDigits(String(value ?? '').normalize('NFC').replace(/<br\s*\/?\s*>/gi, '\n').replace(/<\/?[a-z][^>]*>/gi, '').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\uFFFD\uE000-\uF8FF]/g, '').replace(/[ \t]+/g, ' ').trim()); }
function evidenceKind(source) { const type = String(source?.type || ''); if (type.includes('กฎหมาย')) return 'ข้อกฎหมาย / ระเบียบ / ประกาศ / คำสั่ง'; if (type.includes('คู่มือ')) return 'คู่มือปฏิบัติงาน'; return 'แนวปฏิบัติ / บทเรียน / ตัวอย่างการทำงาน'; }
function formatAnswer(value) {
  const normalized = cleanUiText(value).replace(/\*\*(.*?)\*\*/gs, '$1').replace(/__(.*?)__/gs, '$1').replace(/`/g, '');
  const safe = escapeHtml(normalized).replace(/\[(\d+)\]/g, '<sup class="citation">[$1]</sup>');
  return safe.split(/\n\s*\n/).map(block => {
    const lines = block.split('\n').map(line => line.trim()).filter(Boolean);
    if (!lines.length) return '';
    if (lines.length >= 2 && lines.every(line => line.includes('|')) && /^\|?\s*:?-{3,}/.test(lines[1].replace(/\|/g, ''))) {
      const cells = line => line.replace(/^\|/, '').replace(/\|$/, '').split('|').map(cell => cell.trim());
      const headers = cells(lines[0]);
      const rows = lines.slice(2).map(cells);
      return `<div class="answer-table-wrap"><table class="answer-table"><thead><tr>${headers.map(cell => `<th>${cell}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${headers.map((_, index) => `<td>${row[index] || ''}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
    }
    if (lines.every(line => /^[-•*]\s+/.test(line))) return `<ul>${lines.map(line => `<li>${line.replace(/^[-•*]\s+/, '')}</li>`).join('')}</ul>`;
    if (/^#{1,3}\s/.test(lines[0])) return `<h3>${lines.join(' ').replace(/^#{1,3}\s+/, '')}</h3>`;
    return `<p>${lines.join('<br>')}</p>`;
  }).join('');
}
const legalSubcategories = ['รัฐธรรมนูญ', 'พระราชบัญญัติประกอบรัฐธรรมนูญ', 'พระราชบัญญัติ', 'ระเบียบ ประกาศ แนวปฏิบัติ และคำสั่ง กสม.', 'ระเบียบ ประกาศ แนวปฏิบัติและข้อบังคับของสำนักงาน กสม.'];
const workTags = ['งานดิจิทัล', 'งานงบประมาณ งานคลัง', 'งานพัสดุ-จัดซื้อจัดจ้าง งานบุคคล', 'งานสารบรรณ งานบริหารทั่วไป', 'งานคุ้มครอง', 'งานส่งเสริม', 'งานเฝ้าระวัง', 'งานระหว่างประเทศ', 'งานวิจัยและวิชาการ'];

function nav(key, label, icon) { return `<button class="nav ${state.view === key ? 'active' : ''}" data-view="${key}"><i>${glyph(icon)}</i>${label}${key === 'history' ? '<small>เร็ว ๆ นี้</small>' : ''}</button>`; }
function categoryNav(key, label, icon) { const active = state.view === 'library' && state.filter === key; return `<button class="nav category-nav ${active ? 'active' : ''}" data-category="${key}"><i>${glyph(icon)}</i>${label}</button>`; }
function categoryMenu(target) { if (state.view !== 'library' || state.filter !== target) return ''; const options = target === 'กฎหมาย / ระเบียบ' ? legalSubcategories.map(x => `<button class="subnav ${state.subcategory === x ? 'selected' : ''}" data-subcategory="${x}">${x}</button>`).join('') : workTags.map(x => `<button class="subnav ${state.tag === x ? 'selected' : ''}" data-tag="${x}">${x}</button>`).join(''); return `<div class="category-menu">${options}</div>`; }
function appShell(content) { return `<div class="app"><aside class="rail"><div class="identity"><div class="seal">ก</div><div><b>สิทธิพร้อม</b><span>เครื่องมือ กสม.</span></div></div><div class="rail-section">ทำงาน</div>${nav('ask','ถามผู้ช่วย','search')}${nav('library','ฐานอ้างอิง','library')}<div class="rail-section second">ประเภทเอกสารหลัก</div>${categoryNav('กฎหมาย / ระเบียบ','กฎหมาย ระเบียบ แนวปฏิบัติ','file')}${categoryMenu('กฎหมาย / ระเบียบ')}${categoryNav('คู่มือปฏิบัติงาน','คู่มือปฏิบัติงาน','library')}${categoryMenu('คู่มือปฏิบัติงาน')}${categoryNav('บทเรียนการทำงาน','บทเรียนการทำงาน','check')}${categoryMenu('บทเรียนการทำงาน')}${categoryNav('อื่น ๆ','เอกสารอื่น ๆ','file')}<div class="rail-section second">ดูแลระบบ</div>${nav('upload','นำเข้าเอกสาร','upload')}${nav('settings','การตั้งค่า','settings')}<div class="rail-section second history-section">ย้อนหลัง</div>${nav('history','ประวัติการถาม','history')}<div class="rail-status"><span></span><div><b>ฐานอ้างอิงพร้อมใช้</b><small>${state.docs.length.toLocaleString('th-TH')} รายฉบับในระบบ</small></div></div></aside><main class="workspace"><header><div class="location"><span>สำนักงาน กสม.</span><b>/</b><span>${state.view === 'ask' ? 'ถามผู้ช่วย' : state.view === 'library' ? (state.filter === 'ทั้งหมด' ? 'ฐานอ้างอิง' : state.filter) : 'จัดการระบบ'}</span></div><div class="profile"><span class="bell">♧</span><span class="avatar">ทด</span><b>ธนดล</b><span>⌄</span></div></header>${content}</main></div>`; }

function askView() { return `<section class="ask-view"><div class="hero-kicker"><span></span>ผู้ช่วยงานสำนักงานจากฐานอ้างอิงภายใน</div><div class="hero-grid"><div><h1>ค้นให้เจอ <em>อ้างให้ได้</em></h1><p class="hero-copy">เล่าปัญหาการทำงานด้วยภาษาปกติ ผู้ช่วยจะค้นหลักฐานจากกฎหมาย ระเบียบ คู่มือ และบทเรียนจริง แล้วเรียบเรียงคำตอบพร้อมแหล่งอ้างอิงให้ตรวจสอบย้อนกลับได้</p></div><div class="trust-card"><div class="trust-icon">${glyph('shield')}</div><div><b>คำตอบยึดเอกสารจริง</b><p>ผู้ช่วยไม่ใช้ข้อมูลภายนอก<br>และไม่เติมข้อเท็จจริงที่ไม่มีหลักฐาน</p></div></div></div><div class="search-panel"><div class="search-label"><span>${glyph('search')}</span><b>ถามเรื่องที่ต้องการคำตอบ</b><small>กด Enter เพื่อถาม · Shift + Enter ขึ้นบรรทัดใหม่</small></div><textarea id="query" rows="3" placeholder="เช่น หากต้องการเบิกค่าเดินทางไปราชการ ต้องเตรียมหลักฐานอะไรบ้าง">${state.query}</textarea><div class="search-footer"><div class="suggestions"><span>คำถามที่คนมักถาม</span><button data-query="หากได้รับเรื่องร้องเรียน ควรดำเนินการตามขั้นตอนใด">หากได้รับเรื่องร้องเรียน ควรทำอย่างไร</button><button data-query="การจัดซื้อจัดจ้างต้องเตรียมเอกสารและดำเนินการอย่างไร">การจัดซื้อจัดจ้างต้องทำอย่างไร</button><button data-query="การเบิกจ่ายเงินต้องใช้หลักฐานอะไรบ้าง">การเบิกจ่ายเงินต้องใช้หลักฐานอะไร</button></div><button class="search-btn" id="ask">ให้ผู้ช่วยเรียบเรียงคำตอบ <span>${glyph('arrow')}</span></button></div></div><div id="answer"></div><div class="section-bar"><div><span class="section-kicker">แหล่งอ้างอิงล่าสุด</span><h2>เอกสารที่ผู้ช่วยใช้ได้</h2></div><button class="link-btn" data-view="library">ดูฐานอ้างอิง ${glyph('arrow')}</button></div><div class="featured">${state.docs.slice(0, 3).map(card).join('')}</div></section>`; }
function card(d) { return `<article class="document-card"><div class="card-meta"><span class="tag">${escapeHtml(d.type)}</span><span>${escapeHtml(d.record_type || d.recordType || 'รายฉบับ')}</span></div><h3>${escapeHtml(d.title)}</h3><p>${escapeHtml(d.snippet || 'เอกสารอ้างอิงภายในสำนักงาน กสม.')}</p><div class="card-tags">${d.subcategory ? `<span>${escapeHtml(d.subcategory)}</span>` : ''}${(d.tags || []).slice(0,3).map(t=>`<span>${escapeHtml(t)}</span>`).join('')}</div><div class="card-foot"><span>${glyph('file')} ${escapeHtml(d.source_file || d.sourceFile || d.file)}</span><button data-doc="${d.id}">ดูหลักฐาน ${glyph('arrow')}</button></div></article>`; }
function filterPanel() { if (state.filter === 'ทั้งหมด') return ''; const sub = state.filter === 'กฎหมาย / ระเบียบ' ? `<div><b>หมวดหมู่ย่อยของกฎหมาย</b><div class="chip-row">${legalSubcategories.map(x=>`<button class="pill ${state.subcategory===x?'selected':''}" data-filter-sub="${x}">${x}</button>`).join('')}</div></div>` : ''; return `<div class="filter-panel">${sub}<div><b>หมวดหมู่งาน</b><div class="chip-row">${workTags.map(x=>`<button class="pill ${state.tag===x?'selected':''}" data-filter-tag="${x}">${x}</button>`).join('')}</div></div></div>`; }
function libraryView() { return `<section class="library-view"><div class="view-heading"><div><span class="section-kicker">ฐานข้อมูลกลาง</span><h1>${state.filter === 'ทั้งหมด' ? 'คลังความรู้' : escapeHtml(state.filter)} <em>กสม.</em></h1><p>จัดหมวดจากเอกสารจริงใน Supabase เพื่อให้ค้น อ้างอิง และเปิดอ่านต้นฉบับได้</p></div><div class="count-box"><b>${filteredDocs().length.toLocaleString('th-TH')}</b><span>เอกสารในมุมมองนี้</span></div></div><div class="library-toolbar"><label class="filter-search">${glyph('search')}<input id="librarySearch" placeholder="ค้นชื่อเอกสาร เนื้อหา หรือหัวข้อ..." value="${escapeHtml(state.query)}"></label><div class="filter-pills">${['ทั้งหมด','กฎหมาย / ระเบียบ','คู่มือปฏิบัติงาน','บทเรียนการทำงาน','อื่น ๆ'].map(x=>`<button class="pill ${state.filter===x?'selected':''}" data-filter="${x}">${x}</button>`).join('')}</div></div>${filterPanel()}<div id="libraryList" class="library-list">${filteredDocs().map(card).join('')}</div></section>`; }
function filteredDocs() { const q=state.query.toLowerCase(); return state.docs.filter(d=>(state.filter==='ทั้งหมด'||d.type===state.filter)&&(!state.subcategory||state.subcategory==='ทั้งหมด'||(d.subcategory || d.subCategory)===state.subcategory)&&(!state.tag||state.tag==='ทั้งหมด'||(d.tags||[]).includes(state.tag))&&(!q||`${d.title} ${d.type} ${d.snippet} ${d.file} ${(d.tags||[]).join(' ')}`.toLowerCase().includes(q))); }
function adminView() { const upload = state.view === 'upload'; return `<section class="admin-view"><div class="empty-icon">${glyph(upload ? 'upload' : 'settings')}</div><span class="section-kicker">${upload?'จัดการเอกสาร':'ควบคุมระบบ'}</span><h1>${upload?'นำเข้าเอกสาร':'ตั้งค่าการใช้งาน'} <em>อย่างมั่นใจ</em></h1><p class="admin-copy">${upload?'เอกสารที่นำเข้าจะถูกบันทึกใน Supabase Database และไฟล์ต้นฉบับเก็บใน Supabase Storage เพื่อให้ค้น อ้างอิง และเปิดตรวจสอบได้จากระบบเดียว':'กำหนดหลักการใช้งานให้ชัดเจน: ระบบใช้เฉพาะเอกสารที่อยู่ในฐานความรู้และไม่ตอบจากแหล่งภายนอก'}</p>${upload?`<div class="admin-stats"><div><b>${state.stats.documents||0}</b><span>เอกสารใน Supabase</span></div><div><b>${state.stats.searchable||0}</b><span>เอกสารที่มีข้อความค้นได้</span></div></div><div class="admin-note"><span>${glyph('upload')}</span><div><b>ซิงก์จากโฟลเดอร์จริง</b><p>เพิ่มหรือแก้ไขไฟล์ในโฟลเดอร์แล้วกดปุ่มนี้ ระบบจะอัปเดตทะเบียนเอกสาร เนื้อหา และไฟล์ต้นฉบับใน Supabase</p></div></div><button class="search-btn" id="syncDb">ซิงก์ฐานข้อมูล ${glyph('arrow')}</button>`:`<div class="admin-note"><span>${glyph('shield')}</span><div><b>การทำงานที่ตรวจสอบได้</b><p>คำตอบจะแสดงแหล่งอ้างอิง ข้อความหลักฐาน และชื่อไฟล์ทุกครั้ง ผู้ดูแลควรตรวจสอบเอกสารฉบับเต็มก่อนนำไปใช้งานจริง</p></div></div>`}<button class="link-btn" data-view="library">กลับไปคลังความรู้ ${glyph('arrow')}</button></section>`; }
function historyView() { return `<section class="library-view"><div class="view-heading"><div><span class="section-kicker">บันทึกการใช้งาน</span><h1>ประวัติการค้นหา</h1><p>รายการคำค้นที่ถูกบันทึกในฐานข้อมูลภายในระบบ</p></div><div class="count-box"><b>${state.history.length}</b><span>รายการล่าสุด</span></div></div><div class="history-list">${state.history.length ? state.history.map(item=>`<div class="history-row"><span class="history-time">${new Date(item.created_at+'Z').toLocaleString('th-TH')}</span><b>${item.query}</b><span>${item.result_count} ผลลัพธ์</span></div>`).join('') : '<div class="admin-note"><span>◷</span><div><b>ยังไม่มีประวัติการค้นหา</b><p>เมื่อเริ่มค้นจากหน้า “ถามจากเอกสาร” ระบบจะบันทึกคำค้นไว้ที่นี่</p></div></div>'}</div></section>`; }
function aboutView() { return `<section class="about-view"><div class="view-heading"><div><span class="section-kicker">ความโปร่งใสของระบบ</span><h1>เกี่ยวกับ <em>สิทธิพร้อม</em></h1><p>คำอธิบายสถาปัตยกรรม แหล่งข้อมูล และข้อจำกัด เพื่อให้ผู้ใช้เข้าใจว่าคำตอบเกิดขึ้นอย่างไร</p></div></div><div class="about-grid"><article class="about-card about-wide"><span class="section-kicker">ภาพรวมการทำงาน</span><div class="architecture-flow"><div><b>ผู้ใช้</b><small>พิมพ์คำถาม</small></div><i>→</i><div><b>ระบบ RAG</b><small>ค้นจากเอกสารจริง</small></div><i>→</i><div><b>AI Gemini</b><small>เรียบเรียงจากหลักฐาน</small></div><i>→</i><div><b>คำตอบ</b><small>พร้อมอ้างอิงย้อนกลับ</small></div></div></article><article class="about-card"><h3>แหล่งข้อมูล</h3><p>ข้อมูลนำเข้าจากเอกสารที่เผยแพร่ต่อสาธารณะบนเว็บไซต์ของสำนักงานคณะกรรมการสิทธิมนุษยชนแห่งชาติ และจัดเก็บเป็นทะเบียนเอกสารใน Supabase</p><ul><li>PDF และ DOCX ต้นฉบับเก็บใน Storage</li><li>ข้อความจากเอกสารถูกแบ่งเป็นช่วงเพื่อค้นหา</li><li>PDF สแกนผ่าน OCR และระบุข้อความที่อ่านไม่ชัด</li></ul></article><article class="about-card"><h3>AI ทำงานอย่างไร</h3><p>ระบบแปลงคำถามเป็น embedding แล้วค้นหาช่วงข้อความที่เกี่ยวข้องจากฐานข้อมูล จากนั้นส่งเฉพาะหลักฐานที่ค้นพบให้ Gemini เรียบเรียงคำตอบ</p><ul><li>ไม่ค้นเว็บภายนอกระหว่างตอบ</li><li>ไม่ควรแต่งข้อเท็จจริงที่ไม่มีในหลักฐาน</li><li>คำตอบแสดงเอกสารอ้างอิงทุกครั้ง</li></ul></article><article class="about-card about-wide"><h3>ข้อจำกัดและการใช้ผลลัพธ์</h3><div class="limitation-list"><div><b>ความถูกต้องของ OCR</b><span>เอกสารสแกนอาจมีตัวอักษรหรือเลขที่อ่านผิด ต้องตรวจต้นฉบับเสมอ</span></div><div><b>สถานะกฎหมาย</b><span>ระบบไม่รับรองว่าฉบับใดเป็นฉบับล่าสุดหรือยังมีผลใช้บังคับ หากข้อมูลในเอกสารไม่ได้ระบุชัด</span></div><div><b>ขอบเขตคำตอบ</b><span>ระบบตอบได้เท่าที่มีเอกสารในฐานความรู้ ไม่ใช่คำปรึกษาทางกฎหมายและไม่แทนการตรวจสอบโดยเจ้าหน้าที่ผู้รับผิดชอบ</span></div></div></article></div></section>`; }

async function openDoc(id) { const d=state.docs.find(x=>x.id===id); if(!d)return; const fileUrl=`/api/documents/${encodeURIComponent(d.id)}/file`; const m=document.createElement('div'); m.className='modal-wrap'; m.innerHTML=`<div class="modal reader-modal"><button class="modal-x">${glyph('close')}</button><div class="reader-head"><span class="tag">${escapeHtml(d.type)} · ${escapeHtml(d.record_type || d.recordType || 'รายฉบับ')}</span><a class="evidence-open" href="${fileUrl}" target="_blank" rel="noopener">เปิดต้นฉบับ ${glyph('arrow')}</a></div><h2>${escapeHtml(d.title)}</h2><div class="modal-file">${glyph('file')} ${escapeHtml(d.file)}<br><small>${escapeHtml(d.version_status || d.versionStatus || 'รอการยืนยันสถานะ')}</small></div><div class="reader-content"><div class="result loading">กำลังเตรียมเนื้อหาเอกสาร...</div></div><div class="modal-actions"><button class="link-btn modal-x">ปิด</button></div></div>`; document.body.append(m);m.querySelectorAll('.modal-x').forEach(x=>x.onclick=()=>m.remove()); try { const response=await fetch(`/api/documents/${encodeURIComponent(d.id)}/content`); const content=await response.json(); m.querySelector('.reader-content').innerHTML=`<div class="reader-note">เนื้อหาที่แสดงมาจากการดึงข้อความในเอกสารต้นฉบับ ควรเปิดต้นฉบับตรวจทานเมื่อใช้เป็นหลักฐานทางราชการ</div>${formatAnswer(content.content_text || 'ยังไม่มีข้อความที่ค้นได้ในเอกสารฉบับนี้')}`; } catch(error) { m.querySelector('.reader-content').innerHTML=`<div class="no-result"><b>อ่านเนื้อหาไม่ได้</b><p>${escapeHtml(error.message)}</p></div>`; } }
function syncProfile(){ const profile=$('.profile'); if(!profile||!state.user)return; const name=state.user.user_metadata?.full_name || state.user.user_metadata?.name || state.user.email?.split('@')[0] || 'ผู้ใช้งาน'; const avatar=name.trim().slice(0,1); const avatarEl=profile.querySelector('.avatar'); const nameEl=profile.querySelector('b'); if(avatarEl)avatarEl.textContent=avatar; if(nameEl)nameEl.textContent=name; }
function syncAdminVisibility(){ const adminButtons=document.querySelectorAll('[data-view="upload"],[data-view="settings"]'); adminButtons.forEach(button=>{button.hidden=!state.isAdmin;}); if(!state.isAdmin){document.querySelectorAll('.rail-section').forEach(section=>{if(['ดูแลระบบ'].includes(section.textContent.trim()))section.hidden=true;});} }
function syncAboutLink(){ const profile=$('.profile'); if(!profile||profile.querySelector('#aboutLink'))return; const link=document.createElement('button');link.id='aboutLink';link.className='about-link';link.textContent='เกี่ยวกับระบบ';link.onclick=()=>{state.view='about';render();};profile.append(link); }
async function askQuestion(query){ const q=String(query||'').trim(); const answerBox=$('#answer'); if(!answerBox)return; if(!q){ answerBox.innerHTML='<div class="no-result"><b>พิมพ์คำถามก่อน</b><p>เล่าปัญหาหรือขั้นตอนงานที่ต้องการตรวจสอบจากเอกสารภายใน</p></div>'; return; } state.query=q; answerBox.innerHTML='<div class="answer-card loading">กำลังพิจารณาคำถามและค้นหลักฐานจากเอกสาร...</div>'; try { const response=await fetch(`/api/ask?q=${encodeURIComponent(q)}`); const data=await response.json(); if(!response.ok)throw new Error(data.error||data.detail||'ระบบตอบคำถามขัดข้อง'); if(!data.found){ answerBox.innerHTML=`<div class="no-result"><b>ยังไม่พบหลักฐานที่ตรงพอ</b><p>${escapeHtml(data.message||'ลองปรับคำถามให้ระบุเรื่อง ขั้นตอน หรือเอกสารที่เกี่ยวข้องมากขึ้น')}</p></div>`; return; } const sources=(data.sources||[]).map((source,index)=>`<article class="evidence"><div class="evidence-title"><span class="citation-badge">${escapeHtml(source.citation||`[${index+1}]`)}</span><b>${escapeHtml(toArabicDigits(source.title||'เอกสารอ้างอิง'))}</b></div><p>${escapeHtml(toArabicDigits(source.evidence||'ไม่มีข้อความย่อจากหลักฐาน'))}</p><div class="evidence-foot"><span>${escapeHtml(toArabicDigits(source.sourceFile||source.file||''))}</span><a class="evidence-open" href="/api/documents/${encodeURIComponent(source.id)}/file" target="_blank" rel="noopener">เปิดต้นฉบับ ${glyph('arrow')}</a></div></article>`).join(''); answerBox.innerHTML=`<section class="answer-card"><div class="answer-head"><span class="section-kicker">คำตอบจากเอกสารภายใน</span><span class="answer-query">${escapeHtml(q)}</span></div><div class="result-summary">${formatAnswer(data.answer||'ยังไม่สามารถเรียบเรียงคำตอบจากหลักฐานได้')}</div>${sources?`<div class="evidence-heading"><b>หลักฐานที่ใช้ประกอบคำตอบ</b><span>${sources?`${data.sources.length} รายการ`:''}</span></div><div class="evidence-grid">${sources}</div>`:''}</section>`; } catch(error){ answerBox.innerHTML=`<div class="no-result"><b>ระบบตอบคำถามไม่ได้</b><p>${escapeHtml(error.message)}</p></div>`; } }
async function askQuestion(query) {
  const q = String(query || '').trim();
  const answerBox = $('#answer');
  const askButton = $('#ask');
  if (!answerBox) return;
  if (!q) { answerBox.innerHTML = '<div class="no-result"><b>พิมพ์คำถามก่อน</b><p>เล่าปัญหาหรือขั้นตอนงานที่ต้องการตรวจสอบจากเอกสารภายใน</p></div>'; return; }
  state.query = q;
  if (askButton) { askButton.disabled = true; askButton.dataset.originalLabel = askButton.textContent; askButton.innerHTML = 'กำลังค้นหลักฐาน <span class="button-spinner"></span>'; }
  const stages = ['กำลังทำความเข้าใจคำถาม', 'กำลังค้นเอกสารและข้อความที่เกี่ยวข้อง', 'กำลังตรวจแหล่งอ้างอิง', 'กำลังเรียบเรียงคำตอบ'];
  answerBox.innerHTML = `<section class="ai-progress"><div class="progress-orb"><span></span></div><div><span class="section-kicker">ผู้ช่วยกำลังทำงาน</span><h3 id="aiProgressTitle">${stages[0]}</h3><p>ระบบจะใช้เฉพาะเอกสารที่อยู่ในฐานอ้างอิงภายใน</p></div><div class="progress-steps">${stages.map((stage, index) => `<div class="progress-step ${index === 0 ? 'active' : ''}" data-step="${index}"><span>${index + 1}</span>${stage}</div>`).join('')}</div></section>`;
  let progressIndex = 0;
  const progressTimer = setInterval(() => { progressIndex = Math.min(progressIndex + 1, stages.length - 1); const title = $('#aiProgressTitle'); if (title) title.textContent = stages[progressIndex]; document.querySelectorAll('.progress-step').forEach((step, index) => step.classList.toggle('active', index <= progressIndex)); }, 900);
  try {
    const response = await fetch(`/api/ask?q=${encodeURIComponent(q)}`);
    const data = await response.json();
    if (!response.ok) throw new Error(data.error || data.detail || 'ระบบตอบคำถามขัดข้อง');
    if (!data.found) { answerBox.innerHTML = `<div class="no-result"><b>ยังไม่พบหลักฐานที่ตรงพอ</b><p>${escapeHtml(data.message || 'ลองปรับคำถามให้ระบุเรื่อง ขั้นตอน หรือเอกสารที่เกี่ยวข้องมากขึ้น')}</p></div>`; return; }
    const sources = (data.sources || []).map((source, index) => `<article class="evidence"><div class="evidence-title"><span class="citation-badge">${escapeHtml(source.citation || `[${index + 1}]`)}</span><b>${escapeHtml(toArabicDigits(source.title || 'เอกสารอ้างอิง'))}</b></div><p>${escapeHtml(cleanUiText(source.evidence || 'ไม่มีข้อความย่อจากหลักฐาน'))}</p><div class="evidence-foot"><span class="evidence-kind">${escapeHtml(evidenceKind(source))}</span><span class="evidence-actions"><button class="evidence-detail" data-doc-detail="${escapeHtml(source.id)}">ดูรายละเอียด</button><a class="evidence-open" href="/api/documents/${encodeURIComponent(source.id)}/file" target="_blank" rel="noopener">เปิดต้นฉบับ ${glyph('arrow')}</a></span></div></article>`).join('');
    answerBox.innerHTML = `<section class="answer-workspace"><article class="answer-main answer-card"><div class="answer-head"><span class="section-kicker">คำตอบจากเอกสารภายใน</span><span class="answer-query">${escapeHtml(q)}</span></div><div class="result-summary">${formatAnswer(data.answer || 'ยังไม่สามารถเรียบเรียงคำตอบจากหลักฐานได้')}</div></article><aside class="answer-sources"><div class="sources-head"><span class="section-kicker">ตรวจสอบย้อนกลับ</span><h3>เอกสารอ้างอิง</h3><span>${data.sources.length} รายการ</span></div>${sources}</aside></section>`;
    answerBox.querySelectorAll('[data-doc-detail]').forEach(button => { button.onclick = () => { const doc = state.docs.find(item => item.id === button.dataset.docDetail); if (doc) openDoc(doc.id); }; });
  } catch (error) { answerBox.innerHTML = `<div class="no-result"><b>ระบบตอบคำถามไม่ได้</b><p>${escapeHtml(error.message)}</p></div>`; }
  finally { clearInterval(progressTimer); if (askButton) { askButton.disabled = false; askButton.textContent = askButton.dataset.originalLabel || 'ให้ผู้ช่วยเรียบเรียงคำตอบ'; } }
}
function openDocumentEditor(modal, doc){ const content=doc.content_text||''; const reader=modal.querySelector('.reader-content'); reader.innerHTML=`<div class="document-editor"><label>ชื่อเอกสารจริง<input id="editTitle" value="${escapeHtml(doc.title||'')}"></label><label>เนื้อหาเอกสาร<textarea id="editContent" rows="24">${escapeHtml(content)}</textarea></label><div class="editor-actions"><button class="search-btn" id="saveDocument">บันทึกและสร้างดัชนีใหม่</button><button class="link-btn" id="cancelDocumentEdit">ยกเลิก</button></div><p class="reader-note">เมื่อบันทึก ระบบจะอัปเดตเนื้อหาและสร้าง embedding ใหม่เพื่อให้ค้นจาก RAG ได้ทันที</p></div>`; modal.querySelector('#cancelDocumentEdit').onclick=()=>{modal.remove();openDoc(doc.id)}; modal.querySelector('#saveDocument').onclick=async()=>{const button=modal.querySelector('#saveDocument');button.disabled=true;button.textContent='กำลังบันทึกและสร้างดัชนี...';try{const response=await fetch(`/api/documents/${encodeURIComponent(doc.id)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:modal.querySelector('#editTitle').value,content_text:modal.querySelector('#editContent').value})});const result=await response.json();if(!response.ok)throw new Error(result.error||'บันทึกไม่สำเร็จ');doc.title=result.title;doc.content_text=modal.querySelector('#editContent').value;modal.remove();await init();openDoc(doc.id);}catch(error){button.disabled=false;button.textContent='บันทึกและสร้างดัชนีใหม่';alert(error.message);}}; }
function watchReaderActions(){ document.querySelectorAll('.reader-modal:not([data-edit-ready])').forEach(modal=>{modal.dataset.editReady='true';const doc=state.docs.find(item=>item.title===modal.querySelector('h2')?.textContent);if(!doc)return;const fileMeta=modal.querySelector('.modal-file');if(fileMeta)fileMeta.innerHTML=`เอกสารฉบับจริง: ${escapeHtml(toArabicDigits(doc.title))}<br><small>ไฟล์ต้นฉบับในระบบ: ${escapeHtml(toArabicDigits(doc.source_file||doc.file||''))}</small>`;if(!state.isAdmin)return;const button=document.createElement('button');button.className='link-btn edit-document';button.textContent='แก้ไขรายละเอียด';button.onclick=()=>openDocumentEditor(modal,doc);modal.querySelector('.reader-head')?.append(button);}); }
function bindDocs(){ document.querySelectorAll('.document-card').forEach(card=>{ const trigger=card.querySelector('[data-doc]'); if(!trigger)return; card.dataset.doc=trigger.dataset.doc; const doc=state.docs.find(item=>item.id===trigger.dataset.doc); const footer=card.querySelector('.card-foot span'); if(doc&&footer){footer.textContent='เอกสารฉบับจริง';footer.title=doc.source_file||doc.file||'';} trigger.removeAttribute('data-doc'); card.onclick=()=>openDoc(card.dataset.doc); }); }
function bind(){ document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>{state.view=x.dataset.view;if(state.view==='library'){state.filter='ทั้งหมด';state.subcategory='ทั้งหมด';state.tag='ทั้งหมด';}render();}); document.querySelectorAll('[data-category]').forEach(x=>x.onclick=()=>{state.view='library';state.filter=x.dataset.category;state.subcategory='ทั้งหมด';state.tag='ทั้งหมด';state.query='';render();}); document.querySelectorAll('[data-subcategory]').forEach(x=>x.onclick=()=>{state.view='library';state.filter='กฎหมาย / ระเบียบ';state.subcategory=x.dataset.subcategory;state.tag='ทั้งหมด';render();}); document.querySelectorAll('[data-tag]').forEach(x=>x.onclick=()=>{state.view='library';state.tag=x.dataset.tag;render();}); document.querySelector('#ask')?.addEventListener('click',()=>askQuestion($('#query').value.trim())); document.querySelectorAll('[data-query]').forEach(x=>x.onclick=()=>{const q=x.dataset.query;$('#query').value=q;askQuestion(q)}); document.querySelector('#librarySearch')?.addEventListener('input',e=>{state.query=e.target.value;$('#libraryList').innerHTML=filteredDocs().map(card).join('');bindDocs();}); document.querySelector('#librarySearch')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();state.query=e.target.value;render();}}); document.querySelectorAll('[data-filter]').forEach(x=>x.onclick=()=>{state.filter=x.dataset.filter;state.subcategory='ทั้งหมด';state.tag='ทั้งหมด';render()}); document.querySelectorAll('[data-filter-sub]').forEach(x=>x.onclick=()=>{state.subcategory=x.dataset.filterSub;state.tag='ทั้งหมด';render()}); document.querySelectorAll('[data-filter-tag]').forEach(x=>x.onclick=()=>{state.tag=x.dataset.filterTag;render()}); document.querySelector('#syncDb')?.addEventListener('click',async e=>{e.target.disabled=true;e.target.textContent='กำลังซิงก์...';await fetch('/api/sync',{method:'POST'});await init();}); bindDocs(); }
document.addEventListener('keydown', event => { const input = event.target?.closest?.('#query'); if (!input || event.isComposing) return; if ((event.key === 'Enter' || event.code === 'NumpadEnter') && !event.shiftKey) { event.preventDefault(); event.stopPropagation(); askQuestion(input.value.trim()); } }, true);
const readerObserver = new MutationObserver(() => watchReaderActions());
readerObserver.observe(document.body, { childList: true, subtree: true });
function render(){ if(!state.isAdmin&&['upload','settings'].includes(state.view))state.view='ask'; const content=state.view==='ask'?askView():state.view==='library'?libraryView():state.view==='history'?historyView():state.view==='about'?aboutView():adminView(); document.querySelector('#app').innerHTML=appShell(content);bind();syncProfile();syncAdminVisibility();syncAboutLink(); }
async function init(){ state.docs=(await (await fetch('/api/documents')).json()).documents; state.stats=await (await fetch('/api/stats')).json(); state.history=(await (await fetch('/api/history')).json()).history;render(); }
window.fetch = ((originalFetch) => async (input, options = {}) => { const isProtected = typeof input === 'string' && (input.startsWith('/api/') || input.startsWith('/files/')); if (!isProtected || !supabaseClient) return originalFetch(input, options); const { data } = await supabaseClient.auth.getSession(); const headers = new Headers(options.headers || {}); if (data.session?.access_token) headers.set('Authorization', `Bearer ${data.session.access_token}`); return originalFetch(input, { ...options, headers }); })(window.fetch.bind(window));
initAuth();
const authUiObserver = new MutationObserver(() => { const profile = document.querySelector('.profile'); if (profile && !profile.querySelector('#logout')) { const button = document.createElement('button'); button.id = 'logout'; button.className = 'logout-btn'; button.textContent = 'ออกจากระบบ'; button.onclick = async () => { await supabaseClient.auth.signOut(); }; profile.append(button); } });
authUiObserver.observe(document.querySelector('#app'), { childList: true, subtree: true });
